PillApp/Models/BillVM.cs
using System;

namespace PillApp.Models
{
    public class BillVM
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Value { get; set; }
        public DateTime DateBill { get; set; }
        public Customer Customer { get; set; }
        public Product Product { get; set; }
    }
}

PillApp/Controllers/BillVMsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PillApp.Models;

namespace PillApp.Controllers
{
    public class BillVMsController : Controller
    {
        private readonly AppDbContext _context;
         IWebHostEnvironment webHostEnvironment;
       

        public BillVMsController(AppDbContext context, IWebHostEnvironment webHostEnvi)
        {
            _context = context;
            webHostEnvironment = webHostEnvi;

        }

        // GET: BillVMs
        public async Task<IActionResult> Index(string? searchTerm)
        {
            var appDbContext = _context.BillViewModel
                .AsNoTracking()
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                appDbContext = appDbContext.Where(x => x.Product.Name.Contains(searchTerm));
            }

            var result = await appDbContext
                .Select(x => new BillVM
                {
                    Id = x.Id,
                    ProductId = x.ProductId,
                    Product = x.Product,
                    Customer = x.Customer,
                    DateBill = x.DateBill,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Value = (x.Quantity * x.Price),
                })
                .ToListAsync();

            return View(result);
        }


        // GET: BillVMs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billVM = await _context.BillViewModel
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billVM == null)
            {
                return NotFound();
            }

            var price = (billVM.Quantity * billVM.Price);

            ViewData["Value"] = (billVM.Quantity * billVM.Price);
            return View(billVM);
        }

        // GET: BillVMs/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id");
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return View();
        }

        // POST: BillVMs/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustomerId,ProductId,Quantity,Price,DateBill")] BillVM billVM)
        {
            if (ModelState.IsValid)
            {
                _context.Add(billVM);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", billVM.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", billVM.ProductId);
            return View(billVM);
        }

        // GET: BillVMs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billVM = await _context.BillViewModel.FindAsync(id);
            if (billVM == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", billVM.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", billVM.ProductId);
            return View(billVM);
        }

        // POST: BillVMs/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerId,ProductId,Quantity,Price,DateBill")] BillVM billVM)
        {
            if (id != billVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billVM);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillVMExists(billVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", billVM.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", billVM.ProductId);
            return View(billVM);
        }

        // GET: BillVMs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billVM = await _context.BillViewModel
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billVM == null)
            {
                return NotFound();
            }

            return View(billVM);
        }

        // POST: BillVMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var billVM = await _context.BillViewModel.FindAsync(id);
            _context.BillViewModel.Remove(billVM);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillVMExists(int id)
        {
            return _context.BillViewModel.Any(e => e.Id == id);
        }


        public ActionResult Exit()
        {
            return View();
        }


        public IActionResult Print()
        {

            string path = webHostEnvironment.WebRootPath + @"\Report\BillReport.rdlc";
        Dictionary<string, string> parameters = new Dictionary<string, string>();
        parameters.Add("Param", "Bill RDLC Report");
            var data = _context.BillVMs;

        LocalReport localReport = new LocalReport(path);
        localReport.AddDataSource("BillDataSet", data);
            var report = localReport.Execute(RenderType.Pdf, 1, parameters, "");

            return File(report.MainStream, "application/pdf");


        }
    }
}

PillApp/Views/BillVMs/Create.cshtml
@model PillApp.Models.BillVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>الفاتورة</h4>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateBill" class="control-label"></label>
                <input asp-for="DateBill" class="form-control" />
                <span asp-validation-for="DateBill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-danger text-white" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PillApp/Views/BillVMs/Delete.cshtml
@model PillApp.Models.BillVM

@{
    ViewData["Title"] = "Delete";
}

<h1>مسح الفاتورة</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateBill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateBill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info text-white" asp-action="Index">Back to List</a>
    </form>
</div>

PillApp/Views/BillVMs/Details.cshtml
@model PillApp.Models.BillVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
  

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Customer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    Value
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Name)
                </th>
                <th></th>
            </tr>
        </thead>

         <tbody>

        <tr>
                <td>
                    @Html.DisplayFor(model => model.Customer.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Product.Code)
                </td>
            <td>
                    @Html.DisplayFor(model => model.Quantity)
            </td>
            <td>
                @Html.DisplayFor(model => model.Price)
            </td>
                <td>
                    @ViewData["Value"]
                 </td>
                <td>
                    @Html.DisplayFor(model => model.Product.Name)
                </td>
         </tbody>
        </table>

</div>
<div>
    <a class="btn btn-success text-white" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="btn btn-info text-white" asp-action="Index">Back to List</a>
</div>

PillApp/Views/BillVMs/Edit.cshtml
@model PillApp.Models.BillVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>الفاتورة</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateBill" class="control-label"></label>
                <input asp-for="DateBill" class="form-control" />
                <span asp-validation-for="DateBill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info text-white" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PillApp/Views/BillVMs/Index.cshtml
@model IEnumerable<PillApp.Models.BillVM>

@{
    ViewData["Title"] = "Index";
}


<div class="btns ">
    <a class="btn btn-info text-white" asp-action="Create">Create New</a>
    <a class="btn btn-success text-white" href="javascript:window.print()">Click to Print This Page</a>
    <a class="btn btn-primary" href="javascript:history.go(-1)">Go back</a>
    <a class="btn btn-danger" href="#" onclick="closeWindow();">Exit</a>
    <a class="btn btn-primary" href="../BillVMs/Print" target="_blank">Print Report</a>
</div>
<br />
<h1>الفاتورة</h1>
<hr /> 
        <dl>
        <dd>
           <span class="h4 text-info">Name : </span> @Model.FirstOrDefault().Customer.Name
        </dd>
        <dd>
        <span class="h4 text-info">Date : </span> @Model.FirstOrDefault().DateBill
        </dd>
    </dl>
    <br />

<form method="get" action="@Url.Action("Index", "BillVMs")" class="m-3">
    <label for="search">Search</label>
    <input type="text" name="searchTerm" id="searchTerm" />
    <button class="btn btn-info" type="submit">Perform search</button>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                Num
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                Value
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Code)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
            <td>
                    <a class="btn btn-info text-white" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn btn-warning text-white" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


<dl>
    <dd>
        <span class="h4 text-info">Total Quantity : </span> @foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                </tr>
        }
    </dd>
    <dd>
        <span class="h4 text-info">Total Price : </span> @Model.Sum(i=>i.Value)
    </dd>
</dl>

<script>
    function closeWindow() {
        window.close();
    }
</script>